[build]
  base = "frontend/"
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

[context.production]
  command = "npm run build"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview]
  command = "npm run build"

[context.deploy-preview.environment]
  NODE_ENV = "production"
  NEXTAUTH_URL = "https://deploy-preview-$REVIEW_ID--whatsapi-bridge-web.netlify.app"

[context.branch-deploy]
  command = "npm run build"

[context.branch-deploy.environment]
  NODE_ENV = "production"

# API Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# Cache static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions
[functions]
  node_bundler = "esbuild"
  directory = ".netlify/functions"

# Preview deployments
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true
