version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    container_name: whatsapp-api-dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
      - PORT=3000
    env_file:
      - .env
    volumes:
      - ./src:/usr/src/app/src
      - ./dist:/usr/src/app/dist
    depends_on:
      redis:
        condition: service_healthy
    command: ["npm", "run", "dev"]
    networks:
      - whatsapp-network

  redis:
    image: redis:7-alpine
    container_name: whatsapp-redis-dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - whatsapp-network

volumes:
  redis_data_dev:

networks:
  whatsapp-network:
    driver: bridge
